
import javax.swing.ButtonModel;

/*
 * April 28th, 2020
 * Erika Graham
 * Rock, paper, scissors game
 */

public class FrmRockPaperScissors extends javax.swing.JFrame {

    /**
     * Creates new form FrmRockPaperScissors
     */
    public FrmRockPaperScissors() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblInstructions1 = new javax.swing.JLabel();
        lblInstructions2 = new javax.swing.JLabel();
        lblImgRock = new javax.swing.JLabel();
        lblImgPaper = new javax.swing.JLabel();
        lblImgScissors = new javax.swing.JLabel();
        lblRoundsWon = new javax.swing.JLabel();
        lblCompChooose = new javax.swing.JLabel();
        lblChose = new javax.swing.JLabel();
        lblFinalMsg = new javax.swing.JLabel();
        btnGo = new javax.swing.JButton();
        RadBtnRock = new javax.swing.JRadioButton();
        RadBtnPaper = new javax.swing.JRadioButton();
        RadBtnScissors = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 33)); // NOI18N
        lblTitle.setText("Rock, Paper, Scissors Game");

        lblInstructions1.setText("Welcome to the classic rock, paper, scissors game. This game has 5 rounds.  ");

        lblInstructions2.setText("Choose your gesture and click \"Go\"");

        lblImgRock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rock.png"))); // NOI18N

        lblImgPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paper.png"))); // NOI18N

        lblImgScissors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scissors.png"))); // NOI18N

        lblRoundsWon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRoundsWon.setText("Result:");

        lblCompChooose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCompChooose.setText("Computer chose:");

        lblChose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblFinalMsg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnGo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGo.setText("Go");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        BtnGroup1.add(RadBtnRock);
        RadBtnRock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RadBtnRock.setText("rock");

        BtnGroup1.add(RadBtnPaper);
        RadBtnPaper.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RadBtnPaper.setText("paper");

        BtnGroup1.add(RadBtnScissors);
        RadBtnScissors.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RadBtnScissors.setText("scissors");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addComponent(lblTitle))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addComponent(lblInstructions1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(172, 172, 172)
                            .addComponent(lblInstructions2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblRoundsWon)
                            .addGap(73, 73, 73)
                            .addComponent(lblFinalMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblImgRock, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(RadBtnRock)
                                    .addGap(34, 34, 34)))
                            .addGap(61, 61, 61)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblImgPaper)
                                    .addGap(70, 70, 70)
                                    .addComponent(lblImgScissors, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(RadBtnPaper))))))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCompChooose)
                .addGap(18, 18, 18)
                .addComponent(lblChose, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RadBtnScissors)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblInstructions1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstructions2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCompChooose)
                    .addComponent(lblChose, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImgRock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImgPaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImgScissors, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadBtnPaper)
                    .addComponent(RadBtnRock)
                    .addComponent(RadBtnScissors))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(lblFinalMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRoundsWon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void ComputerChoice (){
        
        //making the computer choose a random number between 1 and 3
        int CompChose = (int)Math.round(Math.random()*2+1);
        //this displays the result of the computer's choice.
        //1 represents rock, 2 = paper, 3 = scissors.
        if (CompChose == 1){
            lblChose.setText("rock");
        } else if (CompChose == 2){
            lblChose.setText("paper");
        } else if (CompChose == 3){
            lblChose.setText("scissors");
        }
        
    }
    
    public void ResultCalculated (String user, String comp){
        
        if((user.equals("rock") && comp.equals("scissors"))||(user.equals("paper") && comp.equals("rock"))||(user.equals("scissors") && comp.equals("paper"))){
            lblFinalMsg.setText("You won");
        } else if ((comp.equals("rock") && user.equals("scissors"))||(comp.equals("paper") && user.equals("rock"))||(comp.equals("scissors") && user.equals("paper"))){ //if statement when user loses
            lblFinalMsg.setText("You lost");
        } else if (user.equals(comp)){ //if statement when there's a draw
            lblFinalMsg.setText("It's a draw");
        }
    }
    
    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        
        String rock = RadBtnRock.getText();
        String paper = RadBtnPaper.getText();
        String scissors = RadBtnScissors.getText();
        
        String [] userchoices = new String [5];
        String [] computerchoices = new String [5];
        
        for (int i =0;i<=4;i++) {  
            
            if (RadBtnRock.isSelected()){
                   //array that stores the user's choices
                userchoices[i]="rock";
                //this method makes the computer choose and then displays the result.
                ComputerChoice();
                //this array stores the computer's choices
                computerchoices [i]= lblChose.getText();
                //this method calculates wether the ser won, lost or if it was a draw.
                ResultCalculated(userchoices[i],computerchoices[i]);
                
            } else if (RadBtnPaper.isSelected()){
                
                userchoices[i]="paper";
                ComputerChoice();
                computerchoices [i]= lblChose.getText();
                
                ResultCalculated(userchoices[i],computerchoices[i]);

            } else if (RadBtnScissors.isSelected()){
                
                userchoices[i]="scissors";
                ComputerChoice();
                computerchoices [i]= lblChose.getText();
                
                ResultCalculated(userchoices[i],computerchoices[i]);
            }
        }
    }//GEN-LAST:event_btnGoActionPerformed
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRockPaperScissors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRockPaperScissors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRockPaperScissors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRockPaperScissors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRockPaperScissors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGroup1;
    private javax.swing.JRadioButton RadBtnPaper;
    private javax.swing.JRadioButton RadBtnRock;
    private javax.swing.JRadioButton RadBtnScissors;
    private javax.swing.JButton btnGo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblChose;
    private javax.swing.JLabel lblCompChooose;
    private javax.swing.JLabel lblFinalMsg;
    private javax.swing.JLabel lblImgPaper;
    private javax.swing.JLabel lblImgRock;
    private javax.swing.JLabel lblImgScissors;
    private javax.swing.JLabel lblInstructions1;
    private javax.swing.JLabel lblInstructions2;
    private javax.swing.JLabel lblRoundsWon;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
